{
 "title": "Data rates",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "camsci1",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(size_bytes) FROM file_origins WHERE creation_time BETWEEN $__timeFrom() AND $__timeTo() AND origin_path LIKE '%/camsci1_%.xrif';"
    }
   ]
  },
  {
   "title": "camvisx",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(size_bytes) FROM file_origins WHERE creation_time BETWEEN $__timeFrom() AND $__timeTo() AND origin_path LIKE '%/camvisx_%.fits';"
    }
   ]
  },
  {
   "title": "camwfs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(size_bytes) FROM file_origins WHERE creation_time BETWEEN $__timeFrom() AND $__timeTo() AND origin_path LIKE '%/camwfs_%.xrif';"
    }
   ]
  },
  {
   "title": "camflowfs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(size_bytes) FROM file_origins WHERE creation_time BETWEEN $__timeFrom() AND $__timeTo() AND origin_path LIKE '%/camflowfs_%.xrif';"
    }
   ]
  },
  {
   "title": "camacq",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(size_bytes) FROM file_origins WHERE creation_time BETWEEN $__timeFrom() AND $__timeTo() AND origin_path LIKE '%/camacq_%.xrif';"
    }
   ]
  },
  {
   "title": "dm00",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(size_bytes) FROM file_origins WHERE creation_time BETWEEN $__timeFrom() AND $__timeTo() AND origin_path LIKE '%/dm00disp%.xrif';"
    }
   ]
  },
  {
   "title": "Other data",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(size_bytes)\nFROM\n  file_origins\nWHERE\n  creation_time BETWEEN $__timeFrom()\n  AND $__timeTo()\n  AND origin_path NOT LIKE '%.xrif';"
    }
   ]
  },
  {
   "title": "camsci2",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(size_bytes) FROM file_origins WHERE creation_time BETWEEN $__timeFrom() AND $__timeTo() AND origin_path LIKE '%/camsci2_%.xrif';"
    }
   ]
  },
  {
   "title": "camlowfs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(size_bytes) FROM file_origins WHERE creation_time BETWEEN $__timeFrom() AND $__timeTo() AND origin_path LIKE '%/camlowfs_%.xrif';"
    }
   ]
  },
  {
   "title": "camllowfs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(size_bytes) FROM file_origins WHERE creation_time BETWEEN $__timeFrom() AND $__timeTo() AND origin_path LIKE '%/camllowfs_%.xrif';"
    }
   ]
  },
  {
   "title": "camtip",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(size_bytes) FROM file_origins WHERE creation_time BETWEEN $__timeFrom() AND $__timeTo() AND origin_path LIKE '%/camtip_%.xrif';"
    }
   ]
  },
  {
   "title": "dm01",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(size_bytes) FROM file_origins WHERE creation_time BETWEEN $__timeFrom() AND $__timeTo() AND origin_path LIKE '%/dm01disp%.xrif';"
    }
   ]
  },
  {
   "title": "dm02",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(size_bytes) FROM file_origins WHERE creation_time BETWEEN $__timeFrom() AND $__timeTo() AND origin_path LIKE '%/dm02disp%.xrif';"
    }
   ]
  },
  {
   "title": "Observations",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "select\n  ts,\n  CASE\n    when (msg ->> 'observing') :: bool = true THEN (msg ->> 'obsName')\n    Else Null\n  end as observing\nfrom\n  telem\nwhere\n  device = 'observers'\n  and ts between $__timeFrom()\n  AND $__timeTo();"
    },
    {
     "rawSql": "with target as (select\n  ts,\n  CASE\n    WHEN msg ->> 'catObj' = 'UNKNOWN'\n    OR msg ->> 'catObj' = 'Pointing'\n    OR msg ->> 'catObj' LIKE '%***%' THEN NULL\n    ELSE msg ->> 'catObj'\n  END as object,\n  (SELECT DISTINCT ON (tcsitelem.ts) msg->>'domeStat'\n    FROM telem as tcsitelem\n    WHERE telem.device = 'tcsi'\n   \tand ec = 'telem_teldata'\n   \tAND tcsitelem.ts between $__timeFrom() AND $__timeTo() \n    AND tcsitelem.ts <= telem.ts\n    ORDER BY ts DESC LIMIT 1) as val\nfrom\n  telem\nwhere\n  device = 'tcsi'\n  AND ec = 'telem_telcat'\n  and ts between $__timeFrom() AND $__timeTo() \n)\nselect ts, CASE WHEN val = '1' then object else null end as object from target;\n\n\n\n\n\n\n\n\n\n"
    }
   ]
  },
  {
   "title": "Science cameras",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "rawSql": "WITH hours AS (\n  SELECT generate_series(\n           date_trunc('hour', ($__timeFrom())::timestamptz ),\n           date_trunc('hour', ($__timeTo())::timestamptz ),\n           interval '1 hour'\n         ) AS hour\n)\nSELECT\n  -- to_char(hours.hour, 'YYYY-MM-DD HH24:MI:SS') AS hour_start,\n  hours.hour,\n  COALESCE(SUM(file_origins.size_bytes), 0) / (60 * 60) AS camsci1\nFROM\n  hours\nLEFT JOIN\n  file_origins ON date_trunc('hour', file_origins.creation_time) = hours.hour\n               AND file_origins.origin_path LIKE '%camsci1%.xrif'\nGROUP BY\n  hours.hour\nORDER BY\n  hours.hour;"
    },
    {
     "rawSql": "WITH hours AS (\n  SELECT generate_series(\n           date_trunc('hour', ($__timeFrom())::timestamptz ),\n           date_trunc('hour', ($__timeTo())::timestamptz ),\n           interval '1 hour'\n         ) AS hour\n)\nSELECT\n  -- to_char(hours.hour, 'YYYY-MM-DD HH24:MI:SS') AS hour_start,\n  hours.hour,\n  COALESCE(SUM(file_origins.size_bytes), 0) / (60 * 60) AS camsci2\nFROM\n  hours\nLEFT JOIN\n  file_origins ON date_trunc('hour', file_origins.creation_time) = hours.hour\n               AND file_origins.origin_path LIKE '%camsci2%.xrif'\nGROUP BY\n  hours.hour\nORDER BY\n  hours.hour;"
    },
    {
     "rawSql": "WITH hours AS (\n  SELECT generate_series(\n           date_trunc('hour', ($__timeFrom())::timestamptz ),\n           date_trunc('hour', ($__timeTo())::timestamptz ),\n           interval '1 hour'\n         ) AS hour\n)\nSELECT\n  -- to_char(hours.hour, 'YYYY-MM-DD HH24:MI:SS') AS hour_start,\n  hours.hour,\n  COALESCE(SUM(file_origins.size_bytes), 0) / (60 * 60) AS camvisx\nFROM\n  hours\nLEFT JOIN\n  file_origins ON date_trunc('hour', file_origins.creation_time) = hours.hour\n               AND file_origins.origin_path LIKE '%camvisx%.fits'\nGROUP BY\n  hours.hour\nORDER BY\n  hours.hour;"
    }
   ]
  },
  {
   "title": "Wavefront sensors",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "rawSql": "WITH hours AS (\n  SELECT generate_series(\n           date_trunc('hour', ($__timeFrom())::timestamptz ),\n           date_trunc('hour', ($__timeTo())::timestamptz ),\n           interval '1 hour'\n         ) AS hour\n)\nSELECT\n  -- to_char(hours.hour, 'YYYY-MM-DD HH24:MI:SS') AS hour_start,\n  hours.hour,\n  COALESCE(SUM(file_origins.size_bytes), 0) / (60 * 60) AS camwfs\nFROM\n  hours\nLEFT JOIN\n  file_origins ON date_trunc('hour', file_origins.creation_time) = hours.hour\n               AND file_origins.origin_path LIKE '%camwfs%.xrif'\nGROUP BY\n  hours.hour\nORDER BY\n  hours.hour;"
    },
    {
     "rawSql": "WITH hours AS (\n  SELECT generate_series(\n           date_trunc('hour', ($__timeFrom())::timestamptz ),\n           date_trunc('hour', ($__timeTo())::timestamptz ),\n           interval '1 hour'\n         ) AS hour\n)\nSELECT\n  -- to_char(hours.hour, 'YYYY-MM-DD HH24:MI:SS') AS hour_start,\n  hours.hour,\n  COALESCE(SUM(file_origins.size_bytes), 0) / (60 * 60) AS camlowfs\nFROM\n  hours\nLEFT JOIN\n  file_origins ON date_trunc('hour', file_origins.creation_time) = hours.hour\n               AND file_origins.origin_path LIKE '%camlowfs%.xrif'\nGROUP BY\n  hours.hour\nORDER BY\n  hours.hour;"
    },
    {
     "rawSql": "WITH hours AS (\n  SELECT generate_series(\n           date_trunc('hour', ($__timeFrom())::timestamptz ),\n           date_trunc('hour', ($__timeTo())::timestamptz ),\n           interval '1 hour'\n         ) AS hour\n)\nSELECT\n  -- to_char(hours.hour, 'YYYY-MM-DD HH24:MI:SS') AS hour_start,\n  hours.hour,\n  COALESCE(SUM(file_origins.size_bytes), 0) / (60 * 60) AS camllowfs\nFROM\n  hours\nLEFT JOIN\n  file_origins ON date_trunc('hour', file_origins.creation_time) = hours.hour\n               AND file_origins.origin_path LIKE '%camllowfs%.xrif'\nGROUP BY\n  hours.hour\nORDER BY\n  hours.hour;"
    },
    {
     "rawSql": "WITH hours AS (\n  SELECT generate_series(\n           date_trunc('hour', ($__timeFrom())::timestamptz ),\n           date_trunc('hour', ($__timeTo())::timestamptz ),\n           interval '1 hour'\n         ) AS hour\n)\nSELECT\n  -- to_char(hours.hour, 'YYYY-MM-DD HH24:MI:SS') AS hour_start,\n  hours.hour,\n  COALESCE(SUM(file_origins.size_bytes), 0) / (60 * 60) AS camflowfs\nFROM\n  hours\nLEFT JOIN\n  file_origins ON date_trunc('hour', file_origins.creation_time) = hours.hour\n               AND file_origins.origin_path LIKE '%camflowfs%.xrif'\nGROUP BY\n  hours.hour\nORDER BY\n  hours.hour;"
    }
   ]
  },
  {
   "title": "Other XRIF",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "rawSql": "WITH hours AS (\n  SELECT generate_series(\n           date_trunc('hour', ($__timeFrom())::timestamptz ),\n           date_trunc('hour', ($__timeTo())::timestamptz ),\n           interval '1 hour'\n         ) AS hour\n)\nSELECT\n  -- to_char(hours.hour, 'YYYY-MM-DD HH24:MI:SS') AS hour_start,\n  hours.hour,\n  COALESCE(SUM(file_origins.size_bytes), 0) / (60 * 60) AS other\nFROM\n  hours\nLEFT JOIN\n  file_origins ON date_trunc('hour', file_origins.creation_time) = hours.hour\n               AND file_origins.origin_path LIKE '%.xrif'\n               AND file_origins.origin_path NOT LIKE '%camsci1%.xrif'\n               AND file_origins.origin_path NOT LIKE '%camsci2%.xrif'\n               AND file_origins.origin_path NOT LIKE '%camwfs%.xrif'\n               AND file_origins.origin_path NOT LIKE '%camlowfs%.xrif'\n               AND file_origins.origin_path NOT LIKE '%camacq%.xrif'\n               AND file_origins.origin_path NOT LIKE '%camtip%.xrif'\n               AND file_origins.origin_path NOT LIKE '%dm00disp%.xrif'\n               AND file_origins.origin_path NOT LIKE '%dm01disp%.xrif'\n               AND file_origins.origin_path NOT LIKE '%dm02disp%.xrif'\nGROUP BY\n  hours.hour\nORDER BY\n  hours.hour;"
    },
    {
     "rawSql": "WITH hours AS (\n  SELECT generate_series(\n           date_trunc('hour', ($__timeFrom())::timestamptz ),\n           date_trunc('hour', ($__timeTo())::timestamptz ),\n           interval '1 hour'\n         ) AS hour\n)\nSELECT\n  -- to_char(hours.hour, 'YYYY-MM-DD HH24:MI:SS') AS hour_start,\n  hours.hour,\n  COALESCE(SUM(file_origins.size_bytes), 0) / (60 * 60) AS camacq\nFROM\n  hours\nLEFT JOIN\n  file_origins ON date_trunc('hour', file_origins.creation_time) = hours.hour\n               AND file_origins.origin_path LIKE '%/camacq_%.xrif'\nGROUP BY\n  hours.hour\nORDER BY\n  hours.hour;"
    },
    {
     "rawSql": "WITH hours AS (\n  SELECT generate_series(\n           date_trunc('hour', ($__timeFrom())::timestamptz ),\n           date_trunc('hour', ($__timeTo())::timestamptz ),\n           interval '1 hour'\n         ) AS hour\n)\nSELECT\n  -- to_char(hours.hour, 'YYYY-MM-DD HH24:MI:SS') AS hour_start,\n  hours.hour,\n  COALESCE(SUM(file_origins.size_bytes), 0) / (60 * 60) AS camtip\nFROM\n  hours\nLEFT JOIN\n  file_origins ON date_trunc('hour', file_origins.creation_time) = hours.hour\n               AND file_origins.origin_path LIKE '%/camtip_%.xrif'\nGROUP BY\n  hours.hour\nORDER BY\n  hours.hour;"
    },
    {
     "rawSql": "WITH hours AS (\n  SELECT generate_series(\n           date_trunc('hour', ($__timeFrom())::timestamptz ),\n           date_trunc('hour', ($__timeTo())::timestamptz ),\n           interval '1 hour'\n         ) AS hour\n)\nSELECT\n  -- to_char(hours.hour, 'YYYY-MM-DD HH24:MI:SS') AS hour_start,\n  hours.hour,\n  COALESCE(SUM(file_origins.size_bytes), 0) / (60 * 60) AS dm00\nFROM\n  hours\nLEFT JOIN\n  file_origins ON date_trunc('hour', file_origins.creation_time) = hours.hour\n               AND file_origins.origin_path LIKE '%/dm00disp_%.xrif'\nGROUP BY\n  hours.hour\nORDER BY\n  hours.hour;"
    },
    {
     "rawSql": "WITH hours AS (\n  SELECT generate_series(\n           date_trunc('hour', ($__timeFrom())::timestamptz ),\n           date_trunc('hour', ($__timeTo())::timestamptz ),\n           interval '1 hour'\n         ) AS hour\n)\nSELECT\n  -- to_char(hours.hour, 'YYYY-MM-DD HH24:MI:SS') AS hour_start,\n  hours.hour,\n  COALESCE(SUM(file_origins.size_bytes), 0) / (60 * 60) AS dm01\nFROM\n  hours\nLEFT JOIN\n  file_origins ON date_trunc('hour', file_origins.creation_time) = hours.hour\n               AND file_origins.origin_path LIKE '%/dm01disp%.xrif'\nGROUP BY\n  hours.hour\nORDER BY\n  hours.hour;"
    },
    {
     "rawSql": "WITH hours AS (\n  SELECT generate_series(\n           date_trunc('hour', ($__timeFrom())::timestamptz ),\n           date_trunc('hour', ($__timeTo())::timestamptz ),\n           interval '1 hour'\n         ) AS hour\n)\nSELECT\n  -- to_char(hours.hour, 'YYYY-MM-DD HH24:MI:SS') AS hour_start,\n  hours.hour,\n  COALESCE(SUM(file_origins.size_bytes), 0) / (60 * 60) AS dm02\nFROM\n  hours\nLEFT JOIN\n  file_origins ON date_trunc('hour', file_origins.creation_time) = hours.hour\n               AND file_origins.origin_path LIKE '%/dm02disp%.xrif'\nGROUP BY\n  hours.hour\nORDER BY\n  hours.hour;"
    }
   ]
  },
  {
   "title": "Other data",
   "type": "barchart",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "rawSql": "WITH hours AS (\n  SELECT generate_series(\n           date_trunc('hour', ($__timeFrom())::timestamptz ),\n           date_trunc('hour', ($__timeTo())::timestamptz ),\n           interval '1 hour'\n         ) AS hour\n)\nSELECT\n  -- to_char(hours.hour, 'YYYY-MM-DD HH24:MI:SS') AS hour_start,\n  hours.hour,\n  COALESCE(SUM(file_origins.size_bytes), 0) / (60 * 60) AS other\nFROM\n  hours\nLEFT JOIN\n  file_origins ON date_trunc('hour', file_origins.creation_time) = hours.hour\n               AND file_origins.origin_path NOT LIKE '%.xrif'\nGROUP BY\n  hours.hour\nORDER BY\n  hours.hour;"
    }
   ]
  },
  {
   "title": "Other XRIF",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT\n  creation_time,\n  regexp_replace(origin_path, '^.+[/\\\\]', '') as filename,\n  size_bytes\nFROM\n  file_origins\nWHERE\n  creation_time BETWEEN $__timeFrom()\n  AND $__timeTo()\n  AND origin_path LIKE '%.xrif'\n  AND origin_path NOT LIKE '%camsci1_%.xrif'\n  AND origin_path NOT LIKE '%camsci2_%.xrif'\n  AND origin_path NOT LIKE '%camwfs_%.xrif'\n  AND origin_path NOT LIKE '%camslowfs_%.xrif'\nLIMIT\n  100;"
    }
   ]
  },
  {
   "title": "Other data",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT\n  creation_time,\n  regexp_replace(origin_path, '^.+[/\\\\]', '') as filename,\n  size_bytes\nFROM\n  file_origins\nWHERE\n  creation_time BETWEEN $__timeFrom()\n  AND $__timeTo()\n  AND origin_path NOT LIKE '%.xrif'\n  AND origin_path NOT LIKE '%.bintel'\n  AND origin_path NOT LIKE '%.binlog'\nLIMIT\n  100;"
    }
   ]
  }
 ]
}