{
 "title": "Instrument environment",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "relative humidity",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "with values as (\nselect\n  ts,\n  jsonb_path_query_first(msg, '$.rh')::real as val\nFROM\n  telem\nwhere\n  device = 'rhtweeter'\n  and ts between $__timeFrom()\n  AND $__timeTo()\norder by\n  ts asc\n)\nselect \n  ts,\n  val as rhtweeter\nfrom values;"
    },
    {
     "rawSql": "with values as (\nselect\n  ts,\n  jsonb_path_query_first(msg, '$.rh')::real as val\nFROM\n  telem\nwhere\n  device = 'rhncpc'\n  and ts between $__timeFrom()\n  AND $__timeTo()\norder by\n  ts asc\n)\nselect \n  ts,\n  val as rhncpc\nfrom values;"
    }
   ]
  },
  {
   "title": "relative humidity",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with values as (\nselect\n  ts,\n  jsonb_path_query_first(msg, '$.rh')::real as val\nFROM\n  telem\nwhere\n  device = 'rhtweeter'\n  and ts between $__timeFrom()\n  AND $__timeTo()\norder by\n  ts asc\n)\nselect \n  ts,\n  val as rhtweeter\nfrom values;"
    },
    {
     "rawSql": "with values as (\nselect\n  ts,\n  jsonb_path_query_first(msg, '$.rh')::real as val\nFROM\n  telem\nwhere\n  device = 'rhncpc'\n  and ts between $__timeFrom()\n  AND $__timeTo()\norder by\n  ts asc\n)\nselect \n  ts,\n  val as rhncpc\nfrom values;"
    }
   ]
  },
  {
   "title": "temprack",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "with temps as\n(select\n  ts,\n  jsonb_path_query_first(msg, '$.temps[0]')::real as temp1,\n  jsonb_path_query_first(msg, '$.temps[1]')::real as temp2\nFROM\n  telem\nwhere\n  device = 'temprack'\n  and ec = 'telem_temps'\n  and ts between $__timeFrom()\n  AND $__timeTo()\n) select * FROM temps\nwhere temp1 > 0 and temp2 > 0\norder by\n  ts asc;"
    }
   ]
  },
  {
   "title": "temprack",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with temps as\n(select\n  ts,\n  jsonb_path_query_first(msg, '$.temps[0]')::real as temp1,\n  jsonb_path_query_first(msg, '$.temps[1]')::real as temp2\nFROM\n  telem\nwhere\n  device = 'temprack'\n  and ec = 'telem_temps'\n  and ts between $__timeFrom()\n  AND $__timeTo()\n) select * FROM temps\nwhere temp1 > 0 and temp2 > 0\norder by\n  ts asc;"
    }
   ]
  },
  {
   "title": "cooling pump",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "with camtemps as (\nselect\n  ts,\n  jsonb_path_query_first(msg, '$.liquidTemp')::real as temp\nFROM\n  telem\nwhere\n  device = 'instCool'\n  and ts between $__timeFrom()\n  AND $__timeTo()\norder by\n  ts asc\n)\nselect \n  ts,\n  temp as instCool\nfrom camtemps;"
    },
    {
     "rawSql": "with camtemps as (\nselect\n  ts,\n  jsonb_path_query_first(msg, '$.liquidTemp')::real as temp\nFROM\n  telem\nwhere\n  device = 'labCool'\n  and ts between $__timeFrom()\n  AND $__timeTo()\norder by\n  ts asc\n)\nselect \n  ts,\n  temp as labCool\nfrom camtemps;"
    }
   ]
  },
  {
   "title": "cooling pump temp (ºC)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with camtemps as (\nselect\n  ts,\n  jsonb_path_query_first(msg, '$.liquidTemp')::real as temp\nFROM\n  telem\nwhere\n  device = 'instCool'\n  and ts between $__timeFrom()\n  AND $__timeTo()\norder by\n  ts asc\n)\nselect \n  ts,\n  temp as instCool\nfrom camtemps;"
    },
    {
     "rawSql": "with camtemps as (\nselect\n  ts,\n  jsonb_path_query_first(msg, '$.liquidTemp')::real as temp\nFROM\n  telem\nwhere\n  device = 'labCool'\n  and ts between $__timeFrom()\n  AND $__timeTo()\norder by\n  ts asc\n)\nselect \n  ts,\n  temp as labCool\nfrom camtemps;"
    }
   ]
  },
  {
   "title": "rh sensor temps",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 12, "y": 6 },
   "targets": [
    {
     "rawSql": "with camtemps as (\nselect\n  ts,\n  jsonb_path_query_first(msg, '$.temp')::real as temp\nFROM\n  telem\nwhere\n  device = 'rhtweeter'\n  and ts between $__timeFrom()\n  AND $__timeTo()\norder by\n  ts asc\n)\nselect \n  ts,\n  temp as rhtweeter\nfrom camtemps\nwhere temp > -999;"
    },
    {
     "rawSql": "with camtemps as (\nselect\n  ts,\n  jsonb_path_query_first(msg, '$.temp')::real as temp\nFROM\n  telem\nwhere\n  device = 'rhncpc'\n  and ts between $__timeFrom()\n  AND $__timeTo()\norder by\n  ts asc\n)\nselect \n  ts,\n  temp as rhncpc\nfrom camtemps\nwhere temp > -999;"
    }
   ]
  },
  {
   "title": "dm temps",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with camtemps as (\nselect\n  ts,\n  jsonb_path_query_first(msg, '$.temp')::real as temp\nFROM\n  telem\nwhere\n  device = 'rhtweeter'\n  and ts between $__timeFrom()\n  AND $__timeTo()\norder by\n  ts asc\n)\nselect \n  ts,\n  temp as tweeter\nfrom camtemps\nwhere temp > -999;"
    },
    {
     "rawSql": "with camtemps as (\nselect\n  ts,\n  jsonb_path_query_first(msg, '$.temp')::real as temp\nFROM\n  telem\nwhere\n  device = 'rhncpc'\n  and ts between $__timeFrom()\n  AND $__timeTo()\norder by\n  ts asc\n)\nselect \n  ts,\n  temp as ncpc\nfrom camtemps\nwhere temp > -999;"
    }
   ]
  },
  {
   "title": "computer temps",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "with temps as (\nselect\n  ts,\n  jsonb_path_query_first(msg, '$.temps[0]')::real as temp\nFROM\n  telem\nwhere\n  device = 'sysMonRTC'\n  and ts between $__timeFrom()\n  AND $__timeTo()\norder by\n  ts asc\n)\nselect \n  ts,\n  temp as rtc\nfrom temps\nwhere temp is not null;"
    },
    {
     "rawSql": "with temps as (\nselect\n  ts,\n  jsonb_path_query_first(msg, '$.temps[0]')::real as temp\nFROM\n  telem\nwhere\n  device = 'sysMonAOC'\n  and ts between $__timeFrom()\n  AND $__timeTo()\norder by\n  ts asc\n)\nselect \n  ts,\n  temp as aoc\nfrom temps\nwhere temp is not null;"
    },
    {
     "rawSql": "with temps as (\nselect\n  ts,\n  (SELECT AVG(value::decimal(18,5))\n   FROM jsonb_array_elements(msg->'temps')\n  ) as temp\nFROM\n  telem\nwhere\n  device = 'sysMonICC'\n  and ec = 'telem_coretemps'\n  and ts between $__timeFrom()\n  AND $__timeTo()\norder by\n  ts asc\n)\nselect \n  ts,\n  temp as icc\nfrom temps\nwhere temp is not null;"
    }
   ]
  },
  {
   "title": "computer temps (ºC)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with temps as (\nselect\n  ts,\n  jsonb_path_query_first(msg, '$.temps[0]')::real as temp\nFROM\n  telem\nwhere\n  device = 'sysMonRTC'\n  and ts between $__timeFrom()\n  AND $__timeTo()\norder by\n  ts asc\n)\nselect \n  ts,\n  temp as rtc\nfrom temps\nwhere temp is not null;"
    },
    {
     "rawSql": "with temps as (\nselect\n  ts,\n  jsonb_path_query_first(msg, '$.temps[0]')::real as temp\nFROM\n  telem\nwhere\n  device = 'sysMonAOC'\n  and ts between $__timeFrom()\n  AND $__timeTo()\norder by\n  ts asc\n)\nselect \n  ts,\n  temp as aoc\nfrom temps\nwhere temp is not null;"
    },
    {
     "rawSql": "with temps as (\nselect\n  ts,\n  (SELECT AVG(value::decimal(18,5))\n   FROM jsonb_array_elements(msg->'temps')\n  ) as temp\nFROM\n  telem\nwhere\n  device = 'sysMonICC'\n  and ec = 'telem_coretemps'\n  and ts between $__timeFrom()\n  AND $__timeTo()\norder by\n  ts asc\n)\nselect \n  ts,\n  temp as icc\nfrom temps\nwhere temp is not null;"
    }
   ]
  },
  {
   "title": "camscis",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 12, "y": 12 },
   "targets": [
    {
     "rawSql": "with camtemps as (\nselect\n  ts,\n  jsonb_path_query_first(msg, '$.tempCtrl.temp')::real as temp,\n  jsonb_path_query_first(msg, '$.tempCtrl.setpt')::real as setpt\n  -- ,\n  -- jsonb_path_query_first(msg, '$.temps[1]')::real as temp2\nFROM\n  telem\nwhere\n  ec = 'telem_stdcam'\n  and device = 'camsci1'\n  and ts between $__timeFrom()\n  AND $__timeTo()\norder by\n  ts asc\n)\nselect \n  ts,\n  setpt as camsci1_setpt,\n  case when temp = -999 then null else temp end as camsci1_temp\nfrom camtemps;"
    },
    {
     "rawSql": "with camtemps as (\nselect\n  ts,\n  jsonb_path_query_first(msg, '$.tempCtrl.temp')::real as temp,\n  jsonb_path_query_first(msg, '$.tempCtrl.setpt')::real as setpt\n  -- ,\n  -- jsonb_path_query_first(msg, '$.temps[1]')::real as temp2\nFROM\n  telem\nwhere\n  ec = 'telem_stdcam'\n  and device = 'camsci2'\n  and ts between $__timeFrom()\n  AND $__timeTo()\norder by\n  ts asc\n)\nselect \n  ts,\n  setpt as camsci2_setpt,\n  case when temp = -999 then null else temp end as camsci2_temp\nfrom camtemps;"
    }
   ]
  },
  {
   "title": "camscis",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with camtemps as (\nselect\n  ts,\n  jsonb_path_query_first(msg, '$.tempCtrl.temp')::real as temp,\n  jsonb_path_query_first(msg, '$.tempCtrl.setpt')::real as setpt\n  -- ,\n  -- jsonb_path_query_first(msg, '$.temps[1]')::real as temp2\nFROM\n  telem\nwhere\n  ec = 'telem_stdcam'\n  and device = 'camsci1'\n  and ts between $__timeFrom()\n  AND $__timeTo()\norder by\n  ts asc\n)\nselect \n  ts,\n  setpt as camsci1_setpt,\n  case when temp = -999 then null else temp end as camsci1_temp\nfrom camtemps;"
    },
    {
     "rawSql": "with camtemps as (\nselect\n  ts,\n  jsonb_path_query_first(msg, '$.tempCtrl.temp')::real as temp,\n  jsonb_path_query_first(msg, '$.tempCtrl.setpt')::real as setpt\n  -- ,\n  -- jsonb_path_query_first(msg, '$.temps[1]')::real as temp2\nFROM\n  telem\nwhere\n  ec = 'telem_stdcam'\n  and device = 'camsci2'\n  and ts between $__timeFrom()\n  AND $__timeTo()\norder by\n  ts asc\n)\nselect \n  ts,\n  setpt as camsci2_setpt,\n  case when temp = -999 then null else temp end as camsci2_temp\nfrom camtemps;"
    }
   ]
  },
  {
   "title": "camwfs",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "select\n  ts,\n  case when jsonb_path_query_first(msg, '$.ccd')::real != -999 then jsonb_path_query_first(msg, '$.ccd')::real else null end as ccd,\n  case when jsonb_path_query_first(msg, '$.cpu')::real != -999 then jsonb_path_query_first(msg, '$.cpu')::real else null end as cpu,\n  case when jsonb_path_query_first(msg, '$.water')::real != -999 then jsonb_path_query_first(msg, '$.water')::real else null end as water\n  -- ,\n  -- jsonb_path_query_first(msg, '$.temps[1]')::real as temp2\nFROM\n  telem\nwhere\n  ec = 'ocam_temps'\n  and device = 'camwfs'\n  and ts between $__timeFrom()\n  AND $__timeTo()\norder by\n  ts asc;"
    }
   ]
  },
  {
   "title": "camwfs temps (ºC)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n  ts,\n  case when jsonb_path_query_first(msg, '$.ccd')::real != -999 then jsonb_path_query_first(msg, '$.ccd')::real else null end as ccd,\n  case when jsonb_path_query_first(msg, '$.cpu')::real != -999 then jsonb_path_query_first(msg, '$.cpu')::real else null end as cpu,\n  case when jsonb_path_query_first(msg, '$.water')::real != -999 then jsonb_path_query_first(msg, '$.water')::real else null end as water\n  -- ,\n  -- jsonb_path_query_first(msg, '$.temps[1]')::real as temp2\nFROM\n  telem\nwhere\n  ec = 'ocam_temps'\n  and device = 'camwfs'\n  and ts between $__timeFrom()\n  AND $__timeTo()\norder by\n  ts asc;"
    }
   ]
  }
 ]
}