{
 "title": "Observations",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Seeing History",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "arcsec" } },
   "targets": [
    {
     "rawSql": "SELECT\n  ts,\n  (\n    CASE\n      WHEN (msg ->> 'mag1_fwhm_corr') :: REAL > 0 THEN (msg ->> 'mag1_fwhm_corr') :: REAL\n      ELSE NULL\n    END\n  ) as Baade,\n  (\n    CASE\n      WHEN (msg ->> 'mag2_fwhm_corr') :: REAL > 0 THEN (msg ->> 'mag2_fwhm_corr') :: REAL\n      ELSE NULL\n    END\n  ) as Clay,\n  (\n    CASE\n      WHEN (msg ->> 'dimm_fwhm_corr') :: REAL > 0 THEN (msg ->> 'dimm_fwhm_corr') :: REAL\n      ELSE NULL\n    END\n  ) as DIMM\nFROM\n  telem\nWHERE\n  device = 'tcsi'\n  and ec = 'telem_telsee'\n  and ts >= $__timeFrom()\n  AND ts <= $__timeTo()\n  AND (\n    (msg ->> 'mag1_fwhm_corr') :: REAL > 0\n    OR (msg ->> 'mag2_fwhm_corr') :: REAL > 0\n    OR (msg ->> 'dimm_fwhm_corr') :: REAL > 0\n  )\nORDER BY\n  ts DESC"
    }
   ]
  },
  {
   "title": "Wind speed",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "targets": [
    {
     "rawSql": "SELECT\n  ts,\n  (msg->>'wind')::float as windspeed\nFROM\n  telem\nWHERE\n  device = 'tcsi'\n  and ec = 'telem_telenv'\n  and ts >= $__timeFrom()\n  AND ts <= $__timeTo()\nORDER BY\n  ts ASC"
    }
   ]
  },
  {
   "title": "Observations",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "select\n  ts,\n  CASE\n    when (msg ->> 'observing') :: bool = true THEN (msg ->> 'obsName')\n    Else Null\n  end as observing\nfrom\n  telem\nwhere\n  device = 'observers'\n  and ts between $__timeFrom()\n  AND $__timeTo();"
    },
    {
     "rawSql": "with target as (select\n  ts,\n  CASE\n    WHEN msg ->> 'catObj' = 'UNKNOWN'\n    OR msg ->> 'catObj' = 'Pointing'\n    OR msg ->> 'catObj' LIKE '%***%' THEN NULL\n    ELSE msg ->> 'catObj'\n  END as object,\n  (SELECT DISTINCT ON (tcsitelem.ts) msg->>'domeStat'\n    FROM telem as tcsitelem\n    WHERE telem.device = 'tcsi'\n   \tand ec = 'telem_teldata'\n   \tAND tcsitelem.ts between $__timeFrom() AND $__timeTo() \n    AND tcsitelem.ts <= telem.ts\n    ORDER BY ts DESC LIMIT 1) as val\nfrom\n  telem\nwhere\n  device = 'tcsi'\n  AND ec = 'telem_telcat'\n  and ts between $__timeFrom() AND $__timeTo() \n)\nselect ts, CASE WHEN val = '1' then object else null end as object from target;\n\n\n\n\n\n\n\n\n\n"
    },
    {
     "rawSql": "select\n  ts,\n  case when msg->>'domeStat' = '1' then 'open' when  msg->>'domeStat' = '-1' then 'changing' else null end as domeStat\nfrom\n  telem\nwhere\n  device = 'tcsi'\n  AND ec = 'telem_teldata'\n  and ts between $__timeFrom() AND $__timeTo();\n\n\n\n\n\n\n\n\n\n"
    }
   ]
  },
  {
   "title": "Filters",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT\n  ts,\n  CASE WHEN msg->>'presetName' IS NOT NULL THEN msg ->> 'presetName' ELSE NULL END as fwsci1\nFROM\n  telem\nWHERE\n  ec = 'telem_stage'\n  AND ts BETWEEN $__timeFrom() AND $__timeTo()\n  AND device = 'fwsci1';"
    },
    {
     "rawSql": "SELECT\n  ts,\n  CASE WHEN msg->>'presetName' IS NOT NULL THEN msg ->> 'presetName' ELSE NULL END as fwsci2\nFROM\n  telem\nWHERE\n  ec = 'telem_stage'\n  AND ts BETWEEN $__timeFrom() AND $__timeTo()\n  AND device = 'fwsci2';"
    }
   ]
  },
  {
   "title": "Beamsplitters",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  ts,\n  CASE\n    WHEN msg ->> 'presetName' IS NOT NULL\n    AND msg ->> 'presetName' != 'none' THEN msg ->> 'presetName'\n    ELSE NULL\n  END as scibs\nFROM\n  telem\nWHERE\n  ec = 'telem_stage'\n  AND ts BETWEEN $__timeFrom() AND $__timeTo()\n  AND device = 'stagescibs';"
    },
    {
     "rawSql": "SELECT\n  ts,\n  CASE\n    WHEN msg ->> 'presetName' IS NOT NULL\n    AND msg ->> 'presetName' != 'none' THEN msg ->> 'presetName'\n    ELSE NULL\n  END as wfs\nFROM\n  telem\nWHERE\n  ec = 'telem_stage'\n  AND ts BETWEEN $__timeFrom() AND $__timeTo()\n  AND device = 'stagebs';"
    }
   ]
  },
  {
   "title": "Tracked Data",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(size_bytes) FROM file_origins WHERE creation_time BETWEEN $__timeFrom() AND $__timeTo() ;"
    }
   ]
  },
  {
   "title": "File Inventory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM file_origins WHERE creation_time BETWEEN $__timeFrom() AND $__timeTo() ;"
    }
   ]
  },
  {
   "title": "camsci1 filter",
   "type": "table",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT\n  msg->>'presetName' as filter_name\nFROM telem WHERE msg->>'presetName' is not null and device = 'fwsci1' and ts between $__timeFrom() and $__timeTo() order by filter_name desc;"
    }
   ]
  },
  {
   "title": "camsci1 exptime",
   "type": "table",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT\n  msg->>'exptime' as exptime,\n  msg->>'fps' as fps,\n  msg->>'emGain' as emGain\nFROM telem WHERE\n  device = 'camsci1' and \n  ts between $__timeFrom() and $__timeTo() AND \n  msg->>'exptime' is not null\n;"
    }
   ]
  },
  {
   "title": "camsci2 filter",
   "type": "table",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT\n  msg->>'presetName' as filter_name\nFROM telem WHERE msg->>'presetName' is not null and device = 'fwsci2' and ts between $__timeFrom() and $__timeTo() order by filter_name desc;"
    }
   ]
  },
  {
   "title": "camsci2 exptime",
   "type": "table",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT\n  msg->>'exptime' as exptime,\n  msg->>'fps' as fps,\n  msg->>'emGain' as emGain\nFROM telem WHERE\n  device = 'camsci2' and \n  ts between $__timeFrom() and $__timeTo() AND \n  msg->>'exptime' is not null\n;"
    }
   ]
  },
  {
   "title": "camwfs exptime",
   "type": "table",
   "gridPos": { "h": 5, "w": 5, "x": 16, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT\n  msg->>'exptime' as exptime,\n  msg->>'fps' as fps,\n  msg->>'emGain' as emgain\nFROM telem WHERE\n  device = 'camwfs' and \n  ts between $__timeFrom() and $__timeTo() AND \n  msg->>'exptime' is not null\n;"
    }
   ]
  },
  {
   "title": "fwlyot filter",
   "type": "table",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT\n  msg->>'presetName' as filter_name\nFROM telem WHERE msg->>'presetName' is not null and device = 'fwlyot' and ts between $__timeFrom() and $__timeTo() order by filter_name desc;"
    }
   ]
  },
  {
   "title": "camsci1",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(size_bytes) FROM file_origins WHERE creation_time BETWEEN $__timeFrom() AND $__timeTo() AND origin_path LIKE '%camsci1_%.xrif';"
    }
   ]
  },
  {
   "title": "camsci2",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(size_bytes) FROM file_origins WHERE creation_time BETWEEN $__timeFrom() AND $__timeTo() AND origin_path LIKE '%camsci2_%.xrif';"
    }
   ]
  },
  {
   "title": "Observations",
   "type": "table",
   "gridPos": { "h": 10, "w": 20, "x": 4, "y": 24 },
   "targets": [
    {
     "rawSql": "WITH \n  obs AS (\n    SELECT\n    ts,\n    (msg->>'observing')::bool as observing,\n    msg->>'email' as email,\n    msg->>'obsName' as obsName,\n    msg->>'tgt_name' as tgt_name\n    FROM telem\n    WHERE\n    device = 'observers' AND\n    msg->>'obsName' != ''\n    ORDER BY ts DESC\n  ),\n  edges AS (\n    SELECT \n      ts,\n      observing,\n      LAG(ts) OVER (ORDER BY ts DESC),\n      LAG(observing) OVER (ORDER BY ts DESC) AS next_paired_observing,\n      email,\n      obsName,\n      tgt_name\n    FROM obs\n  ),\n  transitions AS (\n\t\tSELECT ts, email, obsName, tgt_name, next_paired_observing as observing FROM edges WHERE observing != next_paired_observing\n\t),\n  spans AS (\n    SELECT\n      ts,\n      LAG(ts) OVER (ORDER BY ts DESC) AS next_edge_ts,\n    \temail,\n\t    obsName,\n      observing,\n      tgt_name\n    FROM transitions\n\t)\nSELECT\n\tts as start_ts,\n  next_edge_ts as end_ts,\n  email,\n  tgt_name,\n  obsName\nFROM spans\nWHERE \n\tobserving = true AND\n    (\n        tstzrange(ts, next_edge_ts) && \n        tstzrange($__timeFrom(), $__timeTo())\n    )\nORDER BY ts DESC;"
    }
   ]
  },
  {
   "title": "camflowfs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(size_bytes) FROM file_origins WHERE creation_time BETWEEN $__timeFrom() AND $__timeTo() AND origin_path LIKE '%camflowfs_%.xrif';"
    }
   ]
  },
  {
   "title": "camllowfs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(size_bytes) FROM file_origins WHERE creation_time BETWEEN $__timeFrom() AND $__timeTo() AND origin_path LIKE '%camllowfs_%.xrif';"
    }
   ]
  },
  {
   "title": "camwfs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(size_bytes) FROM file_origins WHERE creation_time BETWEEN $__timeFrom() AND $__timeTo() AND origin_path LIKE '%camwfs_%.xrif';"
    }
   ]
  },
  {
   "title": "other",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(size_bytes) FROM file_origins WHERE creation_time BETWEEN $__timeFrom() AND $__timeTo() AND \norigin_path NOT LIKE '%camlowfs_%.xrif' AND\norigin_path NOT LIKE '%camwfs_%.xrif' AND\norigin_path NOT LIKE '%camsci1_%.xrif' AND\norigin_path NOT LIKE '%camsci2_%.xrif';"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "options": {
    "content": "# Retrieve an arbitrary metric time-series\n\n```\n>>> from magaox import db\n>>> db.metric('tcsi', 'dimm_fwhm_corr', start='${__from:date}', end='${__to:date}')\n[{'ts': ..., 'dimm_fwhm_corr': ...}, ...]\n```"
   }
  }
 ]
}