{
 "title": "On-Sky Temperatures",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Weather station",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n  ts,\n  (msg->>'tempout')::float as temp\nFROM\n  telem\nWHERE\n  device = 'tcsi'\n  and ec = 'telem_telenv'\n  and ts >= $__timeFrom()\n  AND ts <= $__timeTo()\nORDER BY\n  ts ASC"
    }
   ]
  },
  {
   "title": "tcsi",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "select\n  ts,\n  jsonb_path_query_first(msg, '$.temptruss')::real as truss,\n  jsonb_path_query_first(msg, '$.tempcell')::real as cell,\n  jsonb_path_query_first(msg, '$.tempseccell')::real as seccell,\n  jsonb_path_query_first(msg, '$.tempamb')::real as amb\nFROM\n  telem\nwhere\n  device = 'tcsi'\n  and ts between $__timeFrom()\n  AND $__timeTo()\norder by\n  ts asc;"
    }
   ]
  },
  {
   "title": "cameras",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "with camtemps as (\nselect\n  ts,\n  jsonb_path_query_first(msg, '$.tempCtrl.temp')::real as temp,\n  jsonb_path_query_first(msg, '$.tempCtrl.setpt')::real as setpt\n  -- ,\n  -- jsonb_path_query_first(msg, '$.temps[1]')::real as temp2\nFROM\n  telem\nwhere\n  ec = 'telem_stdcam'\n  and device = 'camsci1'\n  and ts between $__timeFrom()\n  AND $__timeTo()\norder by\n  ts asc\n)\nselect \n  ts,\n  setpt as camsci1_setpt,\n  case when temp = -999 then null else temp end as camsci1_temp\nfrom camtemps;"
    },
    {
     "rawSql": "with camtemps as (\nselect\n  ts,\n  jsonb_path_query_first(msg, '$.tempCtrl.temp')::real as temp,\n  jsonb_path_query_first(msg, '$.tempCtrl.setpt')::real as setpt\n  -- ,\n  -- jsonb_path_query_first(msg, '$.temps[1]')::real as temp2\nFROM\n  telem\nwhere\n  ec = 'telem_stdcam'\n  and device = 'camsci2'\n  and ts between $__timeFrom()\n  AND $__timeTo()\norder by\n  ts asc\n)\nselect \n  ts,\n  setpt as camsci2_setpt,\n  case when temp = -999 then null else temp end as camsci2_temp\nfrom camtemps;"
    },
    {
     "rawSql": "select\n  ts,\n  case when jsonb_path_query_first(msg, '$.ccd')::real != -999 then jsonb_path_query_first(msg, '$.ccd')::real else null end as camwfs_ccd,\n  case when jsonb_path_query_first(msg, '$.cpu')::real != -999 then jsonb_path_query_first(msg, '$.cpu')::real else null end as camwfs_cpu,\n  case when jsonb_path_query_first(msg, '$.water')::real != -999 then jsonb_path_query_first(msg, '$.water')::real else null end as camwfs_water\n  -- ,\n  -- jsonb_path_query_first(msg, '$.temps[1]')::real as temp2\nFROM\n  telem\nwhere\n  ec = 'ocam_temps'\n  and device = 'camwfs'\n  and ts between $__timeFrom()\n  AND $__timeTo()\norder by\n  ts asc;"
    }
   ]
  },
  {
   "title": "temprack",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "select\n  ts,\n  jsonb_path_query_first(msg, '$.temps[0]')::real as temp1,\n  jsonb_path_query_first(msg, '$.temps[1]')::real as temp2\nFROM\n  telem\nwhere\n  device = 'temprack'\n  and ec = 'telem_temps'\n  and ts between $__timeFrom()\n  AND $__timeTo()\norder by\n  ts asc;"
    }
   ]
  },
  {
   "title": "rh sensor temps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "rawSql": "with camtemps as (\nselect\n  ts,\n  jsonb_path_query_first(msg, '$.temp')::real as temp\nFROM\n  telem\nwhere\n  device = 'rhtweeter'\n  and ts between $__timeFrom()\n  AND $__timeTo()\norder by\n  ts asc\n)\nselect \n  ts,\n  temp as rhtweeter\nfrom camtemps\nwhere temp > -999;"
    },
    {
     "rawSql": "with camtemps as (\nselect\n  ts,\n  jsonb_path_query_first(msg, '$.temp')::real as temp\nFROM\n  telem\nwhere\n  device = 'rhncpc'\n  and ts between $__timeFrom()\n  AND $__timeTo()\norder by\n  ts asc\n)\nselect \n  ts,\n  temp as rhncpc\nfrom camtemps\nwhere temp > -999;"
    }
   ]
  },
  {
   "title": "relative humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "with values as (\nselect\n  ts,\n  jsonb_path_query_first(msg, '$.rh')::real as val\nFROM\n  telem\nwhere\n  device = 'rhtweeter'\n  and ts between $__timeFrom()\n  AND $__timeTo()\norder by\n  ts asc\n)\nselect \n  ts,\n  val as rhtweeter\nfrom values;"
    },
    {
     "rawSql": "with values as (\nselect\n  ts,\n  jsonb_path_query_first(msg, '$.rh')::real as val\nFROM\n  telem\nwhere\n  device = 'rhncpc'\n  and ts between $__timeFrom()\n  AND $__timeTo()\norder by\n  ts asc\n)\nselect \n  ts,\n  val as rhncpc\nfrom values;"
    }
   ]
  },
  {
   "title": "computer temps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "targets": [
    {
     "rawSql": "with temps as (\nselect\n  ts,\n  jsonb_path_query_first(msg, '$.temps[0]')::real as temp\nFROM\n  telem\nwhere\n  device = 'sysMonRTC'\n  and ts between $__timeFrom()\n  AND $__timeTo()\norder by\n  ts asc\n)\nselect \n  ts,\n  temp as rtc\nfrom temps\nwhere temp is not null;"
    },
    {
     "rawSql": "with temps as (\nselect\n  ts,\n  jsonb_path_query_first(msg, '$.temps[0]')::real as temp\nFROM\n  telem\nwhere\n  device = 'sysMonAOC'\n  and ts between $__timeFrom()\n  AND $__timeTo()\norder by\n  ts asc\n)\nselect \n  ts,\n  temp as aoc\nfrom temps\nwhere temp is not null;"
    },
    {
     "rawSql": "with temps as (\nselect\n  ts,\n  (SELECT AVG(value::decimal(18,5))\n   FROM jsonb_array_elements(msg->'temps')\n  ) as temp\nFROM\n  telem\nwhere\n  device = 'sysMonICC'\n  and ec = 'telem_coretemps'\n  and ts between $__timeFrom()\n  AND $__timeTo()\norder by\n  ts asc\n)\nselect \n  ts,\n  temp as icc\nfrom temps\nwhere temp is not null;"
    }
   ]
  },
  {
   "title": "cooling pump",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
   "targets": [
    {
     "rawSql": "with camtemps as (\nselect\n  ts,\n  jsonb_path_query_first(msg, '$.liquidTemp')::real as temp\nFROM\n  telem\nwhere\n  device = 'instCool'\n  and ts between $__timeFrom()\n  AND $__timeTo()\norder by\n  ts asc\n)\nselect \n  ts,\n  temp as instCool\nfrom camtemps;"
    }
   ]
  }
 ]
}