DO $$
BEGIN
CREATE ROLE xsup WITH LOGIN PASSWORD 'extremeAO!';
EXCEPTION WHEN duplicate_object THEN RAISE NOTICE '%, skipping', SQLERRM USING ERRCODE = SQLSTATE;
END
$$;
DO $$
BEGIN
CREATE ROLE xtelem WITH LOGIN PASSWORD 'extremeAO!';
EXCEPTION WHEN duplicate_object THEN RAISE NOTICE '%, skipping', SQLERRM USING ERRCODE = SQLSTATE;
END
$$;
