GRANT pg_read_all_data TO xsup;
GRANT ALL PRIVILEGES ON DATABASE xtelem TO xtelem;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO xtelem;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO xtelem;
